function [ H,Q ] = qr2step( H,Q,u,i1,i2 )
%GORKA ERAÑA ROBLES - This function, apllies the bulge chasing to a matrix
%H. It takes the vector u generated by startqr2step and the deflation rows
%given by backsearch2.
%   It follows the ideas developed in 5.4.

[n,~] = size(H);

for i = i1:i2-2
    
    j = max([i-1,i1]);
    v = transpose(u)*H(i:i+2,j:n);
    H(i:i+2,j:n) = H(i:i+2,j:n) - u*v;
    iu = min([i+3,i2]);
    v = H(1:iu,i:i+2)*u;
    H(1:iu,i:i+2) = H(1:iu,i:i+2) - v*transpose(u);
    v = Q(1:n,i:i+2)*u;
    Q(1:n,i:i+2) = Q(1:n,i:i+2) - v*transpose(u);
    
    if ( i ~= (i2-2) )
        [u,~] = housegen(H(i+1:i+3,i));
    end
    if ( i ~= i1 )
        H(i+1,j) = 0;
        H(i+2,j) = 0;
    end
    
end

if ( i2 > 2 )
    [H(i2-1,i2-2),H(i2,i2-2),c,s] = rotgen(H(i2-1,i2-2),H(i2,i2-2));
    [H(i2-1,i2-1:n),H(i2,i2-1:n)] = rotapp(c,s,H(i2-1,i2-1:n),H(i2,i2-1:n));
    [H(1:i2,i2-1),H(1:i2,i2)] = rotapp(c,s,H(1:i2,i2-1),H(1:i2,i2));
    [Q(1:n,i2-1),Q(1:n,i2)] = rotapp(c,s,Q(1:n,i2-1),Q(1:n,i2));
end

end

